### ISSUE TITLE
Available validation set？

### ISSUE THREAD

**Issue by HBioquant** [Kohulan/DECIMER-Image-Segmentation#11]
Hi! I'm interested in your work. So, any validation set (pdf files from jnatprod, molecules and phytochem) available? Waiting for your answer. Thanks.

**Comment by OBrink** [comment]
Hey HBioquant,

I have uploaded the pdf files of the articles from the journal _Molecules_ and the segmented chemical structures that resulted from processing them. You can find this in Validation/molecules_validation_data.tar.gz. As Kohulan said, we unfortunately cannot share articles from the other journals due to copyright problems. If you have access to these journals, check the .ods-files in /Validation/ to get the ID of the articles that we have used and download them manually. 

- Otto
