### ISSUE TITLE
could you publish your training data sets?

### ISSUE THREAD

**Issue by tbwxmu** [Kohulan/DECIMER-Image-Segmentation#13]
Thanks for your impressive research work. I think it will be more helpful to other researchers if you publish your training data and the way how to curated the training data in detail. If possible, please also supply one Jupyter notebook for the image annotating and training process. 

Thanks

**Comment by Kohulan** [comment]
Hello @tbwxmu 

Due to copyright reasons, we can't publish the training dataset. Curating a training dataset for Mask-RCNN is explained by the matterport team very clearly, please have a look at their repository. https://github.com/matterport/Mask_RCNN 

The rest of the code and validation datasets are available in our repository. Hope this helps :)

-Kohulan.R
